version: '3.8'

services:

  api:
    build: .
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - MYFOOD_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myfood
    volumes:
      - .:/core
    env_file:
      - .env
    networks:
      - myfood

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=myfood
    volumes:
      - .docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - myfood

networks:
  myfood:
    driver: bridge